theme: jekyll-theme-tactile
#remote_theme: "mmistakes/minimal-mistakes@4.20.2"
title: Speech Dynamics Laboratory
plugins:
  - jekyll-include-cache

url:  # should be empty
baseurl:  # should be empty
serve_og_meta: true
